# ===== MySQL =====
spring.datasource.username=root
spring.datasource.password=Mysql@2003

# ===== JWT =====
app.jwt.secret=SportXSecretKeyForJWTTokenGenerationAndValidation2024SecureRandomBase64Encoded

# ===== Razorpay =====
razorpay.key.id=rzp_test_TLO2rhEDkskCFE
razorpay.key.secret=0D0Dz2cCyRWp1YM56xWYDYNX